### ISSUE TITLE
ibus-m17n always crash

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus-m17n#39]
To reproduce:
1. Select a engine on IBus panel menu likes "m17n:mr:inscript2"

```
#0  ibus_m17n_engine_class_init (klass=0x55723ec67850)
    at /root/rpmbuild/BUILD/ibus-m17n-1.4.8/src/engine.c:247
#1  0x00007f2ba0692ec8 in g_type_class_ref () at /lib64/libgobject-2.0.so.0
#2  0x00007f2ba067c66a in g_object_new_valist () at /lib64/libgobject-2.0.so.0
#3  0x00007f2ba067c74d in g_object_new () at /lib64/libgobject-2.0.so.0
#4  0x00007f2ba08be028 in ibus_engine_new_with_typePython Exception <class 'gdb.error'> No type named TypeNode.: 

    (engine_type=, engine_name=0x7f2b8c00b300 "m17n:mr:inscript2", object_path=0x55723ec932c0 "/org/freedesktop/IBus/Engine/1", connection=0x55723e95d100)
    at /root/rpmbuild/BUILD/ibus-1.5.25/src/ibusengine.c:1611
#5  0x00007f2ba08c715a in ibus_factory_real_create_engine
    (factory=0x55723ec72ca0, engine_name=0x7f2b8c00b300 "m17n:mr:inscript2")
    at /root/rpmbuild/BUILD/ibus-1.5.25/src/ibusfactory.c:117


248	    engine_config = ibus_m17n_get_engine_config (engine_name);
(gdb) print engine_name
$5 = (gchar *) 0x55723ed0d7a0 "m17n:k/\345iwU:=Y\363iwU"
```

The engine_name is broken.

And many assertion errors of "m17n != NULL" are also output.
```
% ibus-engine-m17n --ibus
ibus-m17n-Message: 11:33:14.625: skipped m17n:ko:han2 since its rank is lower than 0
ibus-m17n-Message: 11:33:14.626: skipped m17n:ko:romaja since its rank is lower than 0
ibus-m17n-Message: 11:33:14.636: skipped m17n:zh:py since its rank is lower than 0

** (ibus-engine-m17n:712174): CRITICAL **: 11:37:41.679: ibus_m17n_engine_callback: assertion 'm17n != NULL' failed

** (ibus-engine-m17n:712174): CRITICAL **: 11:37:41.679: ibus_m17n_engine_callback: assertion 'm17n != NULL' failed
```

**Comment by mike-fabian** [comment]
https://github.com/ibus/ibus-m17n/releases/tag/1.4.9
